# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/testing-ios/
version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_ios:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    macos:
      xcode: 13.4.1 # Specify the Xcode version to use

    environment:
      FL_OUTPUT_DIR: output

    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout

      - ruby/install-deps

      - restore_cache:
          key: spm-cache-{{ checksum "warpinator-project.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}

      # - run: pod install # Install CocoaPods dependencies
      - run:
          name: fastlane ios test
          command: bundle exec fastlane ios tests

      - run: ls -a output

      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
          destination: scan-output

      - save_cache:
          paths:
            - SourcePackages/
          key: spm-cache-{{ checksum "warpinator-project.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}

  mac_build_only:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#docker-machine-macos-windows-executor
    macos:
      xcode: 13.4.1 # Specify the Xcode version to use

    environment:
      FL_OUTPUT_DIR: output

    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout

      - ruby/install-deps

      - restore_cache:
          key: spm-cache-{{ checksum "warpinator-project.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}

      # - run: pod install # Install CocoaPods dependencies
      # - run:
      #     name: fastlane mac test
      #     command: bundle exec fastlane mac tests

      - run:
          name: fastlane build mac application
          command: bundle exec fastlane mac build
      
      - run:
          name: remove codesigning
          command: codesign --remove-signature release/warpinator-project.app

      # Collect XML test results data to show in the UI, and save the same XML
      # files under test-results folder in the Artifacts tab
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
          destination: scan-output

      - run:
          name: zip warpinator-project.app
          command: zip -r release/warpinator-project.app.zip release/warpinator-project.app

      - store_artifacts:
          path: release/warpinator-project.app.zip
          destination: warpinator-project.app.zip

      - save_cache:
          paths:
            - SourcePackages/
          key: spm-cache-{{ checksum "warpinator-project.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./release
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=0.0.1
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./release/

# Invoke jobs via workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  ios: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build_ios

  mac: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - mac_build_only
      - publish-github-release:
          requires:
            - mac_build_only
          filters:
            # branches:
            #   ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
