# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  lane :tests do
    run_tests(
      scheme: "Tests Shared (iOS)",
      device: "iPhone 13 mini",
      cloned_source_packages_path: "SourcePackages",
      include_simulator_logs: false
    )
  end
  
end

platform :mac do

    before_all do
      setup_circle_ci
    end
  
    lane :tests do
      run_tests(
        scheme: "warpinator-project (macOS)",
        cloned_source_packages_path: "SourcePackages"
      )
    end

    lane :build do
      build_app(  
        scheme: "warpinator-project (macOS)",
        cloned_source_packages_path: "SourcePackages",
        export_method: "mac-application"
      )
    end
end

